### ISSUE TITLE
`setPermissions` not available?

### ISSUE THREAD

**Issue by beeplin** [feathersjs-ecosystem/feathers-permissions#12]
In the source code `setPermissions.js` is not exported to `hooks`? And the content of `setPermissions.js` seems just an old version of `checkPermissions`.

**Comment by jptissot** [comment]
Same problem here. I think the filters branch is a little more up to date. I hope they release this soon as I am starting a new project and hoe to set this up as well.

**Comment by daffl** [comment]
You can always `require('feathers-permissions/hooks/setPermission')`

**Comment by ForsakenHarmony** [comment]
the debug statement in that file still has check-permissions btw

**Comment by ForsakenHarmony** [comment]
when are you gonna release it?

**Comment by jptissot** [comment]
Any updates?

**Comment by marcpaskell** [comment]
+1
