### ISSUE TITLE
Status of this module

### ISSUE THREAD

**Issue by kokujin** [feathersjs-ecosystem/feathers-permissions#27]
What is the status of this module? There is a message in the Readme still stating that its not ready yet

"This module is not published yet."

When can we hope to use it in production?

Thanks

**Comment by eddyystop** [comment]
@ekryski could answer this best, but here is what I know.

A version of feathers-permissions with noteable enhancements has been proved in the wild.

The core team is 6 part-time people and some members are devoting what free time they have to auth and auth docs. This means permissions will be documented and released after auth is 100%.

**Comment by kristianmandrup** [comment]
"A version of feathers-permissions with noteable enhancements has been proved in the wild" 

Where in the wild?

**Comment by HelloEdit** [comment]
+1

**Comment by georgeedwards** [comment]
@eddyystop @ekryski I don't want to pressure as I know you are a small team, but is there any update on this, or notes of what needs doing / what we might be able to help with.

**Comment by eddyystop** [comment]
I doubt ekryski will get around to it any time soon. There was a Medium article published on how to use another package to do Feathers repos. @marshall may have a link to it.

**Comment by marshall** [comment]
@eddyystop gaaah please stop 😆

**Comment by zusamann** [comment]
Why don't we guys start building your own utils till then. I'm using a `role` & a `permission` db with every `user` getting a `role` and `role` having a bunch of `permissions`. 

I kept the first cut very simple with the pattern `service:method`, will add more dimensions later like `service:method:scope` where `scope` defines the ownership hierarchy.

Here is a very small hook that implements the first cut.

```js
import R from 'ramda';

export const authorize = () =>
  iff(
    isProvider('external'),
    async ctx => {
      const userPermissions = R.path(
        ['params', 'user', 'role', 'permissions'],
        ctx
      );
      if (userPermissions) {
        const types = R.pluck('type', userPermissions);
        const hasPermissions = R.any(
          p => p === `${ctx.path}:${ctx.method}`,
          types
        );
        if (!hasPermissions) {
          throw new errors.Forbidden('Not allowed to execute this action.');
        }
      } 
      return ctx;
    }
  );
```

**Comment by TimNZ** [comment]
This makes me want to go back to Parse

**Comment by daffl** [comment]
@TimNZ I'm always happy about constructive criticism but your comment does neither further this discussion or pays my rent so by all means, you are free to do so.

**Comment by TimNZ** [comment]
It was a zero value comment, but wasn't a criticism.
What I should have said was, "Let's implement the parse ACL model".

**Comment by daffl** [comment]
For reference, there are also two great posts, [Easy API Authorization with CASL and Feathers](https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff) and [Access control strategies with FeathersJS](https://blog.feathersjs.com/access-control-strategies-with-feathersjs-72452268739d) on this topic.

Most permission and authorization can be easily implemented in a few lines of code with all the flexibility (and without looking for another module, reading API docs, debugging issues and complaining about it) in a [hook](https://docs.feathersjs.com/guides/basics/hooks.html). All this module is basically doing is this:

```js
const { Forbidden } = require('@feathersjs/errors');

app.service('messages').hooks({
  before(context) {
    const { user, method, path } = context.params;

    if(user.permissions.includes(`${path}:${method}`) || user.permissions.includes(`${path}:*`) || user.permissions.includes(`*:*`)) {
      return context;
    }

    throw new Forbidden('You are not allowed to access this');
  }
});
```

**Comment by TimNZ** [comment]
@daffl Thanks.  I was hasty in my original comment, having not done a thorough read of all the resources yet.  
I'll go through all the docs and blogs and repos and issues  before I write anything again.

**Comment by HelloEdit** [comment]
Both articles very good but they are not up to date, I have no idea how to integrate them cleanly with the latest version.

**Comment by musicformellons** [comment]
Same here

**Comment by musicformellons** [comment]
Yeah, CASL looks really good, but I too find it not easy to integrate and would like it to easily include Postgres integration.

**Comment by daffl** [comment]
The linked articles will still work with the latest version, the only differences it that the module names changed. So `feathers-errors` becomes `@feathersjs/errors` (as outlined in the [migration guide](https://docs.feathersjs.com/migrating.html#feathersjs-npm-scope)).
