### ISSUE TITLE
Allow user to modify his own data

### ISSUE THREAD

**Issue by Bubomir** [feathersjs-ecosystem/feathers-permissions#35]
Hi,

is it possible to allow user edit only his own record ? For example:

    permissions: [ 'users:update:HIS_ID' ]  (service_name:method:ID)

thanks for explanation if is not It would be great implement this feature I guess

**Comment by daffl** [comment]
This is not in the scope of this module and what [feathers-authentication-hooks](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks) should be used for.

**Comment by Bubomir** [comment]
Thank you very much. That is what I was looking for.
